import type { Lesson } from '@/content/types'

export const ch03Lesson: Lesson = {
  id: 'lesson-ch-03-joins-aggregations-subqueries',
  estimatedMinutes: 50,
  sections: [
    {
      id: 'sec-03-basic-joins',
      type: 'markdown',
      level: 'basic',
      title: 'JOIN Dasar',
      content: `## INNER JOIN\n\nINNER JOIN hanya mengembalikan row yang memiliki kecocokan di kedua table. Contoh: menggabungkan users dan orders berdasarkan user_id.\n\n## LEFT JOIN\n\nLEFT JOIN mengembalikan semua row dari table kiri, meskipun tidak ada kecocokan di table kanan. Nilai yang tidak cocok menjadi NULL. Cocok untuk menemukan user yang belum memiliki order.\n\n## RIGHT JOIN dan FULL OUTER JOIN\n\n- **RIGHT JOIN**: kebalikan LEFT JOIN, semua row dari table kanan dipertahankan.\n- **FULL OUTER JOIN**: semua row dari kedua table dipertahankan, NULL di sisi yang tidak cocok.\n\n## Aggregasi Dasar\n\nFungsi aggregasi menghitung satu nilai dari banyak row:\n\n- \`COUNT(*)\`: jumlah row.\n- \`SUM(column)\`: total nilai.\n- \`AVG(column)\`: rata-rata.\n- \`MIN(column)\` / \`MAX(column)\`: nilai terkecil / terbesar.\n\nContoh query aggregasi dengan GROUP BY dan HAVING:\n\nSELECT category_id, COUNT(*) AS product_count, AVG(price) AS avg_price\nFROM products\nGROUP BY category_id\nHAVING COUNT(*) > 5;`,
    },
    {
      id: 'sec-03-js-example',
      type: 'code-example',
      codeExample: {
        id: 'code-03-js',
        filename: 'joins.js',
        language: 'javascript',
        title: 'JavaScript: Join dan Aggregasi Manual',
        code: [
          'const users = [',
          '  { userId: 1, name: \'Alice\' },',
          '  { userId: 2, name: \'Bob\' },',
          ']',
          '',
          'const orders = [',
          '  { orderId: 101, userId: 1, total: 250000 },',
          '  { orderId: 102, userId: 1, total: 120000 },',
          '  { orderId: 103, userId: 2, total: 50000 },',
          ']',
          '',
          '// LEFT JOIN + GROUP BY manual',
          'const report = users.map((u) => {',
          '  const userOrders = orders.filter((o) => o.userId === u.userId)',
          '  return {',
          '    name: u.name,',
          '    orderCount: userOrders.length,',
          '    totalSpent: userOrders.reduce((sum, o) => sum + o.total, 0),',
          '  }',
          '})',
          '',
          'console.log(report)',
          '// [',
          '//   { name: \'Alice\', orderCount: 2, totalSpent: 370000 },',
          '//   { name: \'Bob\', orderCount: 1, totalSpent: 50000 }',
          '// ]',
        ].join('\n'),
        explanation:
          'filter dan reduce pada array mengilustrasikan LEFT JOIN serta fungsi aggregasi COUNT dan SUM. Pada database, optimasi dapat memanfaatkan index di kolom join.',
      },
    },
    {
      id: 'sec-03-intermediate-subqueries',
      type: 'markdown',
      level: 'intermediate',
      title: 'Subquery, EXISTS, dan HAVING',
      content: `## Subquery Independen\n\nSubquery yang tidak bergantung pada query luar dapat dieksekusi sekali. Contoh: mencari product dengan harga di atas rata-rata.\n\nSELECT name, price\nFROM products\nWHERE price > (SELECT AVG(price) FROM products);\n\n## Correlated Subquery\n\nCorrelated subquery bergantung pada row query luar, sehingga dieksekusi sekali per row. Contoh: mencari user yang memiliki order.\n\nSELECT u.name\nFROM users u\nWHERE EXISTS (\n  SELECT 1 FROM orders o WHERE o.user_id = u.user_id\n);\n\n\`EXISTS\` biasanya lebih efisien daripada \`IN\` untuk subquery besar karena berhenti begitu menemukan kecocokan.\n\n## HAVING vs WHERE\n\n- \`WHERE\`: memfilter row sebelum aggregasi.\n- \`HAVING\`: memfilter grup setelah aggregasi.\n\nContoh:\n\nSELECT category_id, AVG(price) AS avg_price\nFROM products\nWHERE active = true\nGROUP BY category_id\nHAVING AVG(price) > 100000;\n\n## Operasi Set\n\n\`UNION\`, \`INTERSECT\`, dan \`EXCEPT\` menggabungkan hasil dari dua query. \`UNION ALL\` lebih cepat daripada \`UNION\` karena tidak menghilangkan duplikat.`,
    },
    {
      id: 'sec-03-ts-example',
      type: 'code-example',
      codeExample: {
        id: 'code-03-ts',
        filename: 'query-builder.ts',
        language: 'typescript',
        title: 'TypeScript: Query Builder Bertipe',
        code: [
          "type Table = 'users' | 'orders' | 'products'",
          '',
          'interface SelectQuery {',
          '  select: string[]',
          '  from: Table',
          '  joins?: { table: Table; on: string; type: \'INNER\' | \'LEFT\' }[]',
          '  where?: string',
          '  groupBy?: string[]',
          '  having?: string',
          '}',
          '',
          'function buildQuery(q: SelectQuery): string {',
          "  let sql = 'SELECT ' + q.select.join(', ') + ' FROM ' + q.from",
          '  if (q.joins) {',
          '    sql += q.joins',
          "      .map((j) => ' ' + j.type + ' JOIN ' + j.table + ' ON ' + j.on)",
          "      .join('')",
          '  }',
          "  if (q.where) sql += ' WHERE ' + q.where",
          "  if (q.groupBy) sql += ' GROUP BY ' + q.groupBy.join(', ')",
          "  if (q.having) sql += ' HAVING ' + q.having",
          '  return sql',
          '}',
          '',
          'const query: SelectQuery = {',
          "  select: ['u.name', 'COUNT(o.order_id) AS order_count'],",
          "  from: 'users',",
          '  joins: [',
          "    { table: 'orders', on: 'u.user_id = o.user_id', type: 'LEFT' },",
          '  ],',
          "  groupBy: ['u.user_id', 'u.name'],",
          '}',
          '',
          'console.log(buildQuery(query))',
        ].join('\n'),
        explanation:
          'Query builder bertipe menjaga struktur SQL agar tidak salah menempatkan clause. Pola ini mendekati ORM query builder seperti Knex atau Kysely.',
      },
    },
    {
      id: 'sec-03-advanced-window',
      type: 'markdown',
      level: 'advanced',
      title: 'Window Functions dan CTE Recursive',
      content: `## Window Functions\n\nWindow functions menghitung nilai di atas sekumpulan row (window) tanpa mengelompokkan hasil menjadi satu baris.\n\nContoh dengan RANK dan LAG:\n\nSELECT\n  user_id,\n  order_id,\n  total,\n  RANK() OVER (PARTITION BY user_id ORDER BY total DESC) AS rank_in_user,\n  LAG(total, 1) OVER (PARTITION BY user_id ORDER BY order_date) AS prev_order_total\nFROM orders;\n\nFungsi umum:\n\n- \`ROW_NUMBER()\`: nomor unik berturut-turut dalam window.\n- \`RANK()\`: peringkat dengan celah untuk nilai sama.\n- \`DENSE_RANK()\`: peringkat tanpa celah.\n- \`LAG(column, n)\` / \`LEAD(column, n)\`: mengakses row sebelumnya atau berikutnya.\n\n## CTE Recursive\n\nCTE recursive berguna untuk data hierarki seperti organisasi atau kategori.\n\nWITH RECURSIVE subordinates AS (\n  SELECT employee_id, name, manager_id, 1 AS level\n  FROM employees\n  WHERE manager_id IS NULL\n\n  UNION ALL\n\n  SELECT e.employee_id, e.name, e.manager_id, s.level + 1\n  FROM employees e\n  INNER JOIN subordinates s ON e.manager_id = s.employee_id\n)\nSELECT * FROM subordinates;\n\nBagian anchor memilih root, lalu recursive member mengikuti relasi hingga tidak ada row baru. Selalu pastikan ada kondisi terminasi untuk mencegah infinite loop.`,
    },
    {
      id: 'sec-03-go-example',
      type: 'code-example',
      codeExample: {
        id: 'code-03-go',
        filename: 'main.go',
        language: 'go',
        title: 'Go: Raw SQL dengan JOIN dan Aggregasi',
        code: [
          'package main',
          '',
          'import (',
          '\t"database/sql"',
          '\t"fmt"',
          '\t"log"',
          '',
          '\t_ "github.com/lib/pq"',
          ')',
          '',
          'type UserSummary struct {',
          '\tName       string',
          '\tOrderCount int',
          '\tTotalSpent float64',
          '}',
          '',
          'func main() {',
          '\tdb, err := sql.Open("postgres", "postgres://user:pass@localhost/shop?sslmode=disable")',
          '\tif err != nil {',
          '\t\tlog.Fatal(err)',
          '\t}',
          '\tdefer db.Close()',
          '',
          '\trows, err := db.Query(',
          '\t\t"SELECT u.name, COUNT(o.order_id) AS order_count, COALESCE(SUM(o.total), 0) AS total_spent " +',
          '\t\t"FROM users u " +',
          '\t\t"LEFT JOIN orders o ON u.user_id = o.user_id " +',
          '\t\t"GROUP BY u.user_id, u.name",',
          '\t)',
          '\tif err != nil {',
          '\t\tlog.Fatal(err)',
          '\t}',
          '\tdefer rows.Close()',
          '',
          '\tfor rows.Next() {',
          '\t\tvar s UserSummary',
          '\t\tif err := rows.Scan(&s.Name, &s.OrderCount, &s.TotalSpent); err != nil {',
          '\t\t\tlog.Fatal(err)',
          '\t\t}',
          '\t\tfmt.Printf("%s: %d order, Rp%.2f\\n", s.Name, s.OrderCount, s.TotalSpent)',
          '\t}',
          '}',
        ].join('\n'),
        explanation:
          'Query JOIN + GROUP BY di Go menghasilkan summary per user. COALESCE mengubah NULL hasil LEFT JOIN menjadi 0 saat user belum memiliki order.',
      },
    },
    {
      id: 'sec-03-summary',
      type: 'callout',
      calloutType: 'info',
      content:
        '**Kesimpulan:** Pahami perilaku setiap jenis JOIN dan urutan eksekusi clause SQL: FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY. Window functions menambah kemampuan analitis tanpa merusak granularity row.',
    },
  ],
}
