import type { Lesson } from '@/content/types'

export const ch02Lesson: Lesson = {
  id: 'lesson-ch-02-sql-crud-ddl',
  estimatedMinutes: 45,
  sections: [
    {
      id: 'sec-02-basic-crud',
      type: 'markdown',
      level: 'basic',
      title: 'CRUD Dasar dengan SQL',
      content: `## Membaca Data dengan SELECT\n\n\`SELECT\` adalah perintah paling sering digunakan untuk membaca data. Bentuk paling sederhana memilih column dari table dengan filter \`WHERE\`.\n\n## Menambah Data dengan INSERT\n\n\`INSERT\` menambahkan satu atau banyak row sekaligus. Untuk insert banyak row, tulis beberapa tuple dalam satu statement.\n\n## Mengubah Data dengan UPDATE\n\nSelalu gunakan \`WHERE\` saat \`UPDATE\` untuk menghindari mengubah seluruh table. Tanpa WHERE, semua row akan ter-update.\n\n## Menghapus Data dengan DELETE\n\nSama seperti \`UPDATE\`, \`DELETE\` harus dibatasi \`WHERE\`.\n\n## DDL Dasar\n\nDDL mengatur struktur database. Contoh operasi:\n\n- \`CREATE TABLE\`: membuat table baru dengan column dan constraint.\n- \`ALTER TABLE\`: mengubah struktur table yang sudah ada.\n- \`DROP TABLE\`: menghapus table.\n\nContoh \`CREATE TABLE\`:\n\nCREATE TABLE products (\n  product_id SERIAL PRIMARY KEY,\n  name VARCHAR(200) NOT NULL,\n  price NUMERIC(12,2) CHECK (price >= 0),\n  stock INT DEFAULT 0\n);`,
    },
    {
      id: 'sec-02-js-example',
      type: 'code-example',
      codeExample: {
        id: 'code-02-js',
        filename: 'crud.js',
        language: 'javascript',
        title: 'JavaScript: CRUD In-Memory dengan ORM-like API',
        code: [
          'const users = []',
          'let nextId = 1',
          '',
          'function create(email, name) {',
          '  const user = { userId: nextId++, email, name, active: true }',
          '  users.push(user)',
          '  return user',
          '}',
          '',
          'function findById(id) {',
          '  return users.find((u) => u.userId === id)',
          '}',
          '',
          'function update(id, changes) {',
          '  const user = findById(id)',
          '  if (!user) return null',
          '  Object.assign(user, changes)',
          '  return user',
          '}',
          '',
          'function remove(id) {',
          '  const idx = users.findIndex((u) => u.userId === id)',
          '  if (idx === -1) return false',
          '  users.splice(idx, 1)',
          '  return true',
          '}',
          '',
          'const alice = create(\'alice@example.com\', \'Alice\')',
          'update(alice.userId, { name: \'Alice Smith\' })',
          'console.log(findById(alice.userId))',
          'remove(alice.userId)',
        ].join('\n'),
        explanation:
          'Operasi create/read/update/delete pada array menggambarkan perilaku CRUD. Bedanya, database SQL menyimpan data persisten dan menegakkan constraint secara otomatis.',
      },
    },
    {
      id: 'sec-02-intermediate-constraints',
      type: 'markdown',
      level: 'intermediate',
      title: 'Constraint, Tipe Data, dan Alter Table',
      content: `## Jenis Constraint\n\nConstraint adalah aturan yang diterapkan database untuk menjaga integritas data.\n\n- **NOT NULL**: column wajib memiliki nilai.\n- **UNIQUE**: tidak boleh ada nilai duplikat dalam column.\n- **PRIMARY KEY**: gabungan NOT NULL dan UNIQUE; identitas unik setiap row.\n- **FOREIGN KEY**: menjaga referensi ke PK di table lain, biasanya dengan \`ON DELETE\` / \`ON UPDATE\`.\n- **CHECK**: memvalidasi ekspresi boolean, misalnya \`CHECK (price >= 0)\`.\n- **DEFAULT**: memberikan nilai awal jika column tidak diisi.\n\n## Memilih Tipe Data\n\nTipe data mempengaruhi ukuran penyimpanan, presisi, dan performa:\n\n- \`INTEGER\` / \`BIGINT\`: bilangan bulat; pilih \`BIGINT\` jika bisa melebihi 2 miliar.\n- \`NUMERIC(p,s)\` / \`DECIMAL\`: untuk nilai uang karena presisi tetap.\n- \`VARCHAR(n)\`: string dengan panjang variabel, lebih hemat dari \`CHAR\` jika panjang tidak tetap.\n- \`TEXT\`: string panjang tanpa batas praktis di PostgreSQL; di MySQL berdampak pada penyimpanan off-row.\n- \`TIMESTAMP WITH TIME ZONE\`: waktu absolut; hindari menyimpan zona waktu di aplikasi saja.\n- \`BOOLEAN\`: flag true/false.\n- \`ENUM\`: himpunan nilai tetap, tapi pertimbangkan referential integrity table terpisah untuk fleksibilitas.\n\n## ALTER TABLE\n\nPerubahan skema yang umum:\n\n- \`ALTER TABLE users ADD COLUMN phone VARCHAR(20);\`\n- \`ALTER TABLE users ALTER COLUMN phone SET NOT NULL;\`\n- \`ALTER TABLE users DROP COLUMN phone;\`\n- \`ALTER TABLE orders ADD CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE RESTRICT;\`\n\nPerhatikan bahwa \`ALTER TABLE\` pada table besar bisa memicu rewrite table dan memblokir table di beberapa engine.`,
    },
    {
      id: 'sec-02-ts-example',
      type: 'code-example',
      codeExample: {
        id: 'code-02-ts',
        filename: 'schema.ts',
        language: 'typescript',
        title: 'TypeScript: DDL Terstruktur dengan Tipe',
        code: [
          "type ColumnType = 'SERIAL' | 'VARCHAR' | 'NUMERIC' | 'BOOLEAN' | 'TIMESTAMPTZ'",
          '',
          'interface ColumnDef {',
          '  name: string',
          '  type: ColumnType',
          '  length?: number',
          '  notNull?: boolean',
          '  defaultValue?: string',
          '  check?: string',
          '}',
          '',
          'interface TableDef {',
          '  name: string',
          '  columns: ColumnDef[]',
          '  primaryKey: string',
          '}',
          '',
          'const productsTable: TableDef = {',
          '  name: \'products\',',
          '  columns: [',
          '    { name: \'product_id\', type: \'SERIAL\', notNull: true },',
          '    { name: \'name\', type: \'VARCHAR\', length: 200, notNull: true },',
          '    { name: \'price\', type: \'NUMERIC\', notNull: true, check: \'price >= 0\' },',
          '    { name: \'stock\', type: \'NUMERIC\', defaultValue: \'0\' },',
          '    { name: \'active\', type: \'BOOLEAN\', defaultValue: \'true\' },',
          '  ],',
          '  primaryKey: \'product_id\',',
          '}',
          '',
          'function generateCreateTable(def: TableDef): string {',
          '  const cols = def.columns',
          '    .map((c) => {',
          '      const parts = [',
          "        c.name,",
          "        c.type === 'VARCHAR' ? 'VARCHAR(' + (c.length ?? 255) + ')' : c.type,",
          "        c.notNull ? 'NOT NULL' : '',",
          "        c.defaultValue ? 'DEFAULT ' + c.defaultValue : '',",
          "        c.check ? 'CHECK (' + c.check + ')' : '',",
          '      ]',
          "      return parts.filter(Boolean).join(' ')",
          '    })',
          "    .join(',\\n  ')",
          '  return (',
          "    'CREATE TABLE ' +",
          "    def.name +",
          "    ' (\\n  ' +",
          "    cols +",
          "    ',\\n  PRIMARY KEY (' +",
          "    def.primaryKey +",
          "    ')\\n);'",
          '  )',
          '}',
          '',
          'console.log(generateCreateTable(productsTable))',
        ].join('\n'),
        explanation:
          'TypeScript menjaga definisi skema tetap konsisten. Dari objek terstruktur kita bisa menghasilkan DDL SQL, mirip dengan migrasi schema-first atau query builder.',
      },
    },
    {
      id: 'sec-02-advanced-cte-generated',
      type: 'markdown',
      level: 'advanced',
      title: 'CTE dan Generated Columns',
      content: `## Common Table Expressions (CTE)\n\nCTE diawali dengan \`WITH\` dan membuat query modular serta dapat direferensi berulang. CTE dapat bersifat non-recursive untuk query modular, atau recursive untuk data hierarki.\n\nContoh non-recursive dengan dua CTE:\n\nWITH active_users AS (\n  SELECT user_id, name\n  FROM users\n  WHERE active = true\n),\nuser_totals AS (\n  SELECT user_id, SUM(total) AS spent\n  FROM orders\n  GROUP BY user_id\n)\nSELECT au.name, COALESCE(ut.spent, 0) AS total_spent\nFROM active_users au\nLEFT JOIN user_totals ut USING (user_id);\n\n## Generated Columns\n\nGenerated column adalah column yang nilainya dihitung dari column lain. Ada dua jenis:\n\n- **VIRTUAL**: dihitung saat dibaca, tidak disimpan fisik.\n- **STORED**: dihitung saat insert/update dan disimpan, cocok untuk query berat.\n\nContoh di PostgreSQL:\n\nCREATE TABLE products (\n  product_id SERIAL PRIMARY KEY,\n  price NUMERIC(12,2),\n  tax_rate NUMERIC(5,2),\n  total_price NUMERIC(12,2) GENERATED ALWAYS AS (price * (1 + tax_rate)) STORED\n);\n\nKeuntungan generated column: satu sumber kebenaran, tidak perlu di-update manual, dan konsisten.`,
    },
    {
      id: 'sec-02-go-example',
      type: 'code-example',
      codeExample: {
        id: 'code-02-go',
        filename: 'main.go',
        language: 'go',
        title: 'Go: CRUD dengan database/sql',
        code: [
          'package main',
          '',
          'import (',
          '\t"database/sql"',
          '\t"fmt"',
          '\t"log"',
          '',
          '\t_ "github.com/lib/pq"',
          ')',
          '',
          'func main() {',
          '\tdb, err := sql.Open("postgres", "postgres://user:pass@localhost/shop?sslmode=disable")',
          '\tif err != nil {',
          '\t\tlog.Fatal(err)',
          '\t}',
          '\tdefer db.Close()',
          '',
          '\t// Create',
          '\t_, err = db.Exec(',
          '\t\t"INSERT INTO users (email, name) VALUES ($1, $2)",',
          '\t\t"alice@example.com", "Alice",',
          '\t)',
          '\tif err != nil {',
          '\t\tlog.Fatal(err)',
          '\t}',
          '',
          '\t// Read',
          '\tvar name string',
          '\tvar email string',
          '\terr = db.QueryRow("SELECT name, email FROM users WHERE user_id = $1", 1).Scan(&name, &email)',
          '\tif err != nil {',
          '\t\tlog.Fatal(err)',
          '\t}',
          '\tfmt.Printf("User: %s <%s>\\n", name, email)',
          '',
          '\t// Update',
          '\t_, err = db.Exec("UPDATE users SET name = $1 WHERE user_id = $2", "Alice Smith", 1)',
          '\tif err != nil {',
          '\t\tlog.Fatal(err)',
          '\t}',
          '',
          '\t// Delete',
          '\t_, err = db.Exec("DELETE FROM users WHERE user_id = $1", 1)',
          '\tif err != nil {',
          '\t\tlog.Fatal(err)',
          '\t}',
          '}',
        ].join('\n'),
        explanation:
          'Go database/sql menyediakan API minimalis: Exec untuk statement tanpa hasil, QueryRow untuk satu row, dan Query untuk banyak row. Parameterized query $1 mencegah SQL injection.',
      },
    },
    {
      id: 'sec-02-summary',
      type: 'callout',
      calloutType: 'info',
      content:
        '**Kesimpulan:** CRUD dan DDL adalah fondasi SQL. Gunakan constraint untuk menjaga integritas, pilih tipe data dengan bijak, dan manfaatkan CTE untuk query yang modular. Ingat: UPDATE dan DELETE tanpa WHERE adalah musuh utama di production.',
    },
  ],
}
