import type { Lesson } from '@/content/types'

export const ch08Lesson: Lesson = {
  id: 'lesson-ch-08-database-design-project',
  estimatedMinutes: 60,
  sections: [
    {
      id: 'sec-08-basic-requirements',
      type: 'markdown',
      level: 'basic',
      title: 'Requirement Gathering',
      content: `## Studi Kasus: Sistem LMS Sederhana\n\nKita akan merancang database untuk Learning Management System (LMS) dengan fitur:\n\n1. **User**: siswa dan instruktur dengan email unik.\n2. **Course**: kursus memiliki judul, deskripsi, dan instruktur.\n3. **Enrollment**: siswa dapat mendaftar ke banyak kursus.\n4. **Lesson**: setiap kursus memiliki banyak lesson.\n5. **Progress**: siswa menyelesaikan lesson dan sistem mencatat completion.\n\n## Langkah Desain\n\n1. Identifikasi entitas: User, Course, Enrollment, Lesson, Progress.\n2. Tentukan atribut utama untuk setiap entitas.\n3. Tentukan relasi dan cardinality.\n4. Gambar ERD.\n5. Terjemahkan ERD ke DDL.\n6. Buat seed data dan uji query.\n\n## ERD Sederhana\n\n- User (1) --- (N) Enrollment (N) --- (1) Course\n- Course (1) --- (N) Lesson\n- User (1) --- (N) Progress (N) --- (1) Lesson\n\nRelasi Enrollment adalah many-to-many antara User dan Course yang diwakili junction table. Progress adalah many-to-many antara User dan Lesson.`,
    },
    {
      id: 'sec-08-js-example',
      type: 'code-example',
      codeExample: {
        id: 'code-08-js',
        filename: 'lms.js',
        language: 'javascript',
        title: 'JavaScript: Model Data LMS',
        code: [
          'const users = [',
          "  { userId: 1, email: 'alice@example.com', name: 'Alice', role: 'student' },",
          "  { userId: 2, email: 'bob@example.com', name: 'Bob', role: 'instructor' },",
          ']',
          '',
          'const courses = [',
          '  { courseId: 1, title: \'Database Basic\', instructorId: 2 },',
          ']',
          '',
          'const enrollments = [',
          '  { enrollmentId: 1, userId: 1, courseId: 1, enrolledAt: \'2026-06-01\' },',
          ']',
          '',
          'const lessons = [',
          '  { lessonId: 1, courseId: 1, title: \'Relational Model\', orderIndex: 1 },',
          ']',
          '',
          'const progress = [',
          '  { progressId: 1, userId: 1, lessonId: 1, completedAt: \'2026-06-02\' },',
          ']',
          '',
          'function getCourseProgress(userId, courseId) {',
          '  const courseLessons = lessons.filter((l) => l.courseId === courseId)',
          '  const completed = progress.filter(',
          '    (p) => p.userId === userId && courseLessons.some((l) => l.lessonId === p.lessonId)',
          '  )',
          '  return {',
          '    total: courseLessons.length,',
          '    completed: completed.length,',
          '    percent: courseLessons.length ? (completed.length / courseLessons.length) * 100 : 0,',
          '  }',
          '}',
          '',
          'console.log(getCourseProgress(1, 1))',
        ].join('\n'),
        explanation:
          'Model in-memory ini menggambarkan entitas dan relasi LMS. Setiap entitas memiliki primary key dan foreign key yang jelas sebelum diterjemahkan ke DDL SQL.',
      },
    },
    {
      id: 'sec-08-intermediate-ddl',
      type: 'markdown',
      level: 'intermediate',
      title: 'DDL dan Index Planning',
      content: `## DDL Lengkap LMS\n\nCREATE TABLE users (\n  user_id BIGSERIAL PRIMARY KEY,\n  email VARCHAR(255) NOT NULL UNIQUE,\n  name VARCHAR(200) NOT NULL,\n  role VARCHAR(20) NOT NULL CHECK (role IN ('student', 'instructor')),\n  created_at TIMESTAMPTZ DEFAULT NOW()\n);\n\nCREATE TABLE courses (\n  course_id BIGSERIAL PRIMARY KEY,\n  instructor_id BIGINT NOT NULL REFERENCES users(user_id),\n  title VARCHAR(200) NOT NULL,\n  description TEXT,\n  created_at TIMESTAMPTZ DEFAULT NOW()\n);\n\nCREATE TABLE enrollments (\n  enrollment_id BIGSERIAL PRIMARY KEY,\n  user_id BIGINT NOT NULL REFERENCES users(user_id),\n  course_id BIGINT NOT NULL REFERENCES courses(course_id),\n  enrolled_at TIMESTAMPTZ DEFAULT NOW(),\n  UNIQUE (user_id, course_id)\n);\n\nCREATE TABLE lessons (\n  lesson_id BIGSERIAL PRIMARY KEY,\n  course_id BIGINT NOT NULL REFERENCES courses(course_id) ON DELETE CASCADE,\n  title VARCHAR(200) NOT NULL,\n  order_index INT NOT NULL,\n  UNIQUE (course_id, order_index)\n);\n\nCREATE TABLE progress (\n  progress_id BIGSERIAL PRIMARY KEY,\n  user_id BIGINT NOT NULL REFERENCES users(user_id),\n  lesson_id BIGINT NOT NULL REFERENCES lessons(lesson_id),\n  completed_at TIMESTAMPTZ DEFAULT NOW(),\n  UNIQUE (user_id, lesson_id)\n);\n\n## Index Planning\n\nBerdasarkan query pattern:\n\n- \`users(email)\`: UNIQUE index untuk login.\n- \`courses(instructor_id)\`: foreign key index untuk query kursus per instruktur.\n- \`enrollments(user_id, course_id)\`: composite unique untuk cek duplikat dan query kursus siswa.\n- \`lessons(course_id, order_index)\`: composite untuk mengambil lesson berurutan.\n- \`progress(user_id, lesson_id)\`: composite untuk progress per siswa.\n\nCREATE INDEX idx_courses_instructor ON courses(instructor_id);\nCREATE INDEX idx_enrollments_user ON enrollments(user_id);\nCREATE INDEX idx_lessons_course_order ON lessons(course_id, order_index);\nCREATE INDEX idx_progress_user_lesson ON progress(user_id, lesson_id);`,
    },
    {
      id: 'sec-08-ts-example',
      type: 'code-example',
      codeExample: {
        id: 'code-08-ts',
        filename: 'migration-plan.ts',
        language: 'typescript',
        title: 'TypeScript: Rencana Migrasi Skema',
        code: [
          'interface Migration {',
          '  id: string',
          '  up: string',
          '  down: string',
          '}',
          '',
          'const migrations: Migration[] = [',
          '  {',
          "    id: '001_create_users',",
          "    up: 'CREATE TABLE users (' +",
          "      'user_id BIGSERIAL PRIMARY KEY,' +",
          "      'email VARCHAR(255) NOT NULL UNIQUE,' +",
          "      'name VARCHAR(200) NOT NULL,' +",
          "      'role VARCHAR(20) NOT NULL,' +",
          "      'created_at TIMESTAMPTZ DEFAULT NOW()' +",
          "    ');',",
          "    down: 'DROP TABLE users;',",
          '  },',
          '  {',
          "    id: '002_create_courses',",
          "    up: 'CREATE TABLE courses (' +",
          "      'course_id BIGSERIAL PRIMARY KEY,' +",
          "      'instructor_id BIGINT NOT NULL REFERENCES users(user_id),' +",
          "      'title VARCHAR(200) NOT NULL,' +",
          "      'description TEXT,' +",
          "      'created_at TIMESTAMPTZ DEFAULT NOW()' +",
          "    ');',",
          "    down: 'DROP TABLE courses;',",
          '  },',
          ']',
          '',
          'function applyMigration(m: Migration) {',
          "  console.log('Applying:', m.id)",
          '  console.log(m.up)',
          '}',
          '',
          'migrations.forEach(applyMigration)',
        ].join('\n'),
        explanation:
          'Migrasi yang terurut dan reversible memudahkan deployment dan rollback. Setiap perubahan skema dicatat dengan versi dan script down untuk pemulihan.',
      },
    },
    {
      id: 'sec-08-advanced-performance',
      type: 'markdown',
      level: 'advanced',
      title: 'Query Pelaporan dan Target Performa',
      content: `## Query Progress per Course\n\nSELECT\n  c.title,\n  u.name AS student,\n  COUNT(l.lesson_id) AS total_lessons,\n  COUNT(p.progress_id) AS completed_lessons\nFROM enrollments e\nJOIN courses c ON e.course_id = c.course_id\nJOIN users u ON e.user_id = u.user_id\nJOIN lessons l ON l.course_id = c.course_id\nLEFT JOIN progress p ON p.lesson_id = l.lesson_id AND p.user_id = u.user_id\nGROUP BY c.course_id, c.title, u.user_id, u.name;\n\n## Query Leaderboard\n\nSELECT\n  u.name,\n  COUNT(p.progress_id) AS completed_count\nFROM users u\nLEFT JOIN progress p ON p.user_id = u.user_id\nWHERE u.role = 'student'\nGROUP BY u.user_id, u.name\nORDER BY completed_count DESC\nLIMIT 10;\n\n## Target Performa Awal\n\n- **Read**: query enrollment dan progress harus di bawah 100 ms pada 10.000 siswa.\n- **Write**: insert enrollment dan progress harus di bawah 50 ms.\n- **Index**: setiap FK dan kolom yang sering difilter harus memiliki index.\n- **Monitoring**: gunakan \`pg_stat_statements\` atau slow query log untuk mendeteksi query yang memburuk.\n\n## Strategi Migrasi\n\n1. Tulis migrasi backward-compatible (tambah kolom nullable atau default dulu).\n2. Jalankan migrasi di staging dengan data representatif.\n3. Gunakan transaction untuk DDL kecil; untuk table besar, pertimbangkan online schema change tool.\n4. Catat waktu migrasi dan rencana rollback.\n5. Setelah deploy, verifikasi query plan dengan EXPLAIN ANALYZE.`,
    },
    {
      id: 'sec-08-go-example',
      type: 'code-example',
      codeExample: {
        id: 'code-08-go',
        filename: 'main.go',
        language: 'go',
        title: 'Go: Seed Data untuk LMS',
        code: [
          'package main',
          '',
          'import (',
          '\t"database/sql"',
          '\t"fmt"',
          '\t"log"',
          '',
          '\t_ "github.com/lib/pq"',
          ')',
          '',
          'func seed(db *sql.DB) error {',
          '\ttx, err := db.Begin()',
          '\tif err != nil {',
          '\t\treturn err',
          '\t}',
          '\tdefer func() {',
          '\t\tif err != nil {',
          '\t\t\t_ = tx.Rollback()',
          '\t\t}',
          '\t}()',
          '',
          '\tvar instructorID int64',
          '\terr = tx.QueryRow(',
          '\t\t"INSERT INTO users (email, name, role) VALUES ($1, $2, $3) RETURNING user_id",',
          '\t\t"bob@example.com", "Bob", "instructor",',
          '\t).Scan(&instructorID)',
          '\tif err != nil {',
          '\t\treturn err',
          '\t}',
          '',
          '\tvar courseID int64',
          '\terr = tx.QueryRow(',
          '\t\t"INSERT INTO courses (instructor_id, title) VALUES ($1, $2) RETURNING course_id",',
          '\t\tinstructorID, "Database Basic",',
          '\t).Scan(&courseID)',
          '\tif err != nil {',
          '\t\treturn err',
          '\t}',
          '',
          '\tfor i := 1; i <= 8; i++ {',
          '\t\t_, err = tx.Exec(',
          '\t\t\t"INSERT INTO lessons (course_id, title, order_index) VALUES ($1, $2, $3)",',
          '\t\t\tcourseID, fmt.Sprintf("Chapter %d", i), i,',
          '\t\t)',
          '\t\tif err != nil {',
          '\t\t\treturn err',
          '\t\t}',
          '\t}',
          '',
          '\treturn tx.Commit()',
          '}',
          '',
          'func main() {',
          '\tdb, err := sql.Open("postgres", "postgres://user:pass@localhost/lms?sslmode=disable")',
          '\tif err != nil {',
          '\t\tlog.Fatal(err)',
          '\t}',
          '\tdefer db.Close()',
          '',
          '\tif err := seed(db); err != nil {',
          '\t\tlog.Fatal(err)',
          '\t}',
          '\tfmt.Println("Seed data committed")',
          '}',
        ].join('\n'),
        explanation:
          'Seed data dibuat dalam satu transaksi agar konsisten. Jika salah satu insert gagal, seluruh seed di-rollback. Pola ini penting untuk setup environment dan testing.',
      },
    },
    {
      id: 'sec-08-summary',
      type: 'callout',
      calloutType: 'info',
      content:
        '**Kesimpulan:** Proyek desain database menggabungkan ERD, normalisasi, DDL, index planning, seed data, dan strategi migrasi. Mulailah dari kebutuhan bisnis, dokumentasikan setiap keputusan, dan verifikasi performa dengan data realistis.',
    },
  ],
}
