import type { Lesson } from '@/content/types'

export const ch07Lesson: Lesson = {
  id: 'lesson-ch-07-views-functions-triggers',
  estimatedMinutes: 45,
  sections: [
    {
      id: 'sec-07-basic-views',
      type: 'markdown',
      level: 'basic',
      title: 'View dan Materialized View',
      content: `## View\n\nView adalah query bernama yang disimpan di database. Setiap kali view di-query, database menjalankan query definisi view tersebut. Contoh view active_user_orders menggabungkan users dan orders serta memfilter user aktif.\n\nKeuntungan view:\n\n- Menyederhanakan query kompleks.\n- Memberikan lapisan abstraksi sehingga aplikasi tidak perlu tahu struktur table dasar.\n- Dapat membatasi akses data dengan membuka hanya kolom tertentu.\n\n## Materialized View\n\nMaterialized view menyimpan hasil query secara fisik, sehingga query menjadi sangat cepat. Namun, datanya perlu di-refresh. Contoh daily_revenue menyimpan agregasi penjualan harian.\n\nMaterialized view cocok untuk dashboard dan laporan yang tidak memerlukan data real-time. REFRESH MATERIALIZED VIEW memperbarui snapshot.`,
    },
    {
      id: 'sec-07-js-example',
      type: 'code-example',
      codeExample: {
        id: 'code-07-js',
        filename: 'view.js',
        language: 'javascript',
        title: 'JavaScript: View sebagai Fungsi Query',
        code: [
          'const users = [',
          '  { userId: 1, name: \'Alice\', active: true },',
          '  { userId: 2, name: \'Bob\', active: false },',
          ']',
          '',
          'const orders = [',
          '  { orderId: 101, userId: 1, total: 250000 },',
          '  { orderId: 102, userId: 2, total: 120000 },',
          ']',
          '',
          'function activeUserOrders() {',
          '  return orders',
          '    .filter((o) => users.find((u) => u.userId === o.userId)?.active)',
          '    .map((o) => ({',
          '      userId: o.userId,',
          '      name: users.find((u) => u.userId === o.userId).name,',
          '      orderId: o.orderId,',
          '      total: o.total,',
          '    }))',
          '}',
          '',
          'console.log(activeUserOrders())',
        ].join('\n'),
        explanation:
          'Fungsi activeUserOrders menggambarkan view: setiap dipanggil, ia menjalankan logika query dasar. Bedanya, database view dapat memanfaatkan index pada table dasar.',
      },
    },
    {
      id: 'sec-07-intermediate-functions',
      type: 'markdown',
      level: 'intermediate',
      title: 'Stored Function dan Procedure',
      content: `## Stored Function\n\nStored function mengembalikan nilai dan dapat digunakan dalam expression atau query. Contoh: get_total_spent(user_id) mengembalikan total pembelian seorang user.\n\nSELECT name, get_total_spent(user_id) AS spent FROM users;\n\n## Stored Procedure\n\nStored procedure tidak mengembalikan nilai secara langsung dan biasanya dipanggil dengan CALL. Procedure cocok untuk operasi yang melibatkan beberapa statement dan kontrol alur. Contoh: deactivate_user mematikan user dan membatalkan order pending sekaligus.\n\n## Kapan Menggunakan?\n\n- **Function**: komputasi reusable dalam SQL, transformasi data, validasi sederhana.\n- **Procedure**: batch operation, logika bisnis yang harus berjalan di database, mengurangi round-trip jaringan.\n\nHindari meletakkan terlalu banyak logika bisnis di database karena sulit di-test, di-version, dan di-deploy.`,
    },
    {
      id: 'sec-07-ts-example',
      type: 'code-example',
      codeExample: {
        id: 'code-07-ts',
        filename: 'functions.ts',
        language: 'typescript',
        title: 'TypeScript: Abstraksi Query Reusable',
        code: [
          'interface Order {',
          '  orderId: number',
          '  userId: number',
          '  total: number',
          "  status: 'pending' | 'paid' | 'cancelled'",
          '}',
          '',
          'function totalSpentByUser(orders: Order[], userId: number): number {',
          '  return orders',
          '    .filter((o) => o.userId === userId)',
          '    .reduce((sum, o) => sum + o.total, 0)',
          '}',
          '',
          'function cancelPendingOrders(orders: Order[], userId: number): Order[] {',
          '  return orders.map((o) =>',
          '    o.userId === userId && o.status === \'pending\'',
          '      ? { ...o, status: \'cancelled\' }',
          '      : o',
          '  )',
          '}',
          '',
          'const orders: Order[] = [',
          '  { orderId: 1, userId: 10, total: 100000, status: \'pending\' },',
          '  { orderId: 2, userId: 10, total: 200000, status: \'paid\' },',
          ']',
          '',
          'console.log(totalSpentByUser(orders, 10))',
          'console.log(cancelPendingOrders(orders, 10))',
        ].join('\n'),
        explanation:
          'Fungsi pure ini mengilustrasikan stored function dan procedure. Di database, fungsi tersebut dieksekusi di server sehingga mengurangi transfer data, tetapi menambah coupling pada skema.',
      },
    },
    {
      id: 'sec-07-advanced-triggers',
      type: 'markdown',
      level: 'advanced',
      title: 'Trigger, Audit Trail, dan Trade-off',
      content: `## Trigger\n\nTrigger adalah blok kode yang dieksekusi otomatis saat terjadi event tertentu pada table. Contoh: trigger AFTER UPDATE OF email ON users mencatat perubahan email ke tabel users_audit.\n\nTrigger sering dipakai untuk:\n\n- Audit trail: mencatat perubahan data.\n- Validasi kompleks yang sulit diwakili constraint sederhana.\n- Sinkronisasi denormalized data.\n- Update aggregated table atau materialized view secara inkremental.\n\n## Kapan Hati-hati?\n\n- **Hidden logic**: trigger membuat perilaku table tidak transparan, menyulitkan debug.\n- **Cascading trigger**: trigger yang memicu trigger lain dapat menyebabkan efek yang sulit diprediksi.\n- **Performa**: trigger dieksekusi per row atau per statement, menambah overhead write.\n- **Testability**: logika di database sulit diuji dengan unit test aplikasi.\n\n## Audit Trail yang Baik\n\n- Simpan old value, new value, who, dan when.\n- Pertimbangkan tabel audit terpisah atau partisi berdasarkan waktu.\n- Gunakan JSONB untuk audit fleksibel jika skema sering berubah.\n- Untuk audit sangat penting, pertimbangkan immutable log (WAL, event log) alih-alih hanya trigger table.`,
    },
    {
      id: 'sec-07-go-example',
      type: 'code-example',
      codeExample: {
        id: 'code-07-go',
        filename: 'main.go',
        language: 'go',
        title: 'Go: Read Model dengan View',
        code: [
          'package main',
          '',
          'import (',
          '\t"database/sql"',
          '\t"fmt"',
          '\t"log"',
          '',
          '\t_ "github.com/lib/pq"',
          ')',
          '',
          'type UserOrder struct {',
          '\tUserID  int64',
          '\tName    string',
          '\tOrderID int64',
          '\tTotal   float64',
          '}',
          '',
          'func main() {',
          '\tdb, err := sql.Open("postgres", "postgres://user:pass@localhost/shop?sslmode=disable")',
          '\tif err != nil {',
          '\t\tlog.Fatal(err)',
          '\t}',
          '\tdefer db.Close()',
          '',
          '\trows, err := db.Query("SELECT user_id, name, order_id, total FROM active_user_orders WHERE total > $1", 100000)',
          '\tif err != nil {',
          '\t\tlog.Fatal(err)',
          '\t}',
          '\tdefer rows.Close()',
          '',
          '\tfor rows.Next() {',
          '\t\tvar uo UserOrder',
          '\t\tif err := rows.Scan(&uo.UserID, &uo.Name, &uo.OrderID, &uo.Total); err != nil {',
          '\t\t\tlog.Fatal(err)',
          '\t\t}',
          '\t\tfmt.Printf("%s (user %d) order #%d Rp%.2f\\n", uo.Name, uo.UserID, uo.OrderID, uo.Total)',
          '\t}',
          '}',
        ].join('\n'),
        explanation:
          'Aplikasi Go membaca dari view active_user_orders seolah-olah itu table biasa. View menyembunyikan kompleksitas JOIN dan filter di belakang antarmuka yang sederhana.',
      },
    },
    {
      id: 'sec-07-summary',
      type: 'callout',
      calloutType: 'info',
      content:
        '**Kesimpulan:** View, function, dan trigger adalah alat powerful untuk abstraksi dan otomasi. Gunakan view untuk menyederhanakan query, function untuk komputasi reusable, dan trigger untuk audit dengan penuh pertimbangan terhadap maintainability dan performa.',
    },
  ],
}
