import type { Lesson } from '@/content/types'

export const ch04Lesson: Lesson = {
  id: 'lesson-ch-04-normalisasi',
  estimatedMinutes: 45,
  sections: [
    {
      id: 'sec-04-basic-normal-forms',
      type: 'markdown',
      level: 'basic',
      title: 'Bentuk Normal Dasar',
      content: `## Mengapa Normalisasi Penting?\n\nNormalisasi adalah proses mengorganisasi data untuk:\n\n- Mengurangi redundansi.\n- Mencegah anomali update, insert, dan delete.\n- Menjaga integritas data melalui constraint.\n\n## 1NF — First Normal Form\n\nSebuah table memenuhi 1NF jika:\n\n1. Setiap cell berisi satu nilai atomic (tidak ada array atau list dalam satu cell).\n2. Setiap column memiliki tipe data yang konsisten.\n3. Tidak ada grup kolom yang berulang.\n\n## 2NF — Second Normal Form\n\nTable memenuhi 2NF jika sudah 1NF dan setiap atribut non-key bergantung penuh pada seluruh primary key (bukan sebagian). Syarat ini relevan ketika PK adalah composite key.\n\n## 3NF — Third Normal Form\n\nTable memenuhi 3NF jika sudah 2NF dan tidak ada transitive dependency: atribut non-key tidak bergantung pada atribut non-key lain.\n\n## Anomali yang Dicegah\n\n- **Insert anomaly**: tidak bisa menyimpan data tertentu karena kekurangan bagian lain dari row.\n- **Update anomaly**: perubahan nilai harus dilakukan di banyak tempat.\n- **Delete anomaly**: menghapus row secara tidak sengaja menghilangkan informasi lain.`,
    },
    {
      id: 'sec-04-js-example',
      type: 'code-example',
      codeExample: {
        id: 'code-04-js',
        filename: 'normalization.js',
        language: 'javascript',
        title: 'JavaScript: Flat Table vs Table Normalisasi',
        code: [
          '// Bentuk flat (belum normalisasi)',
          'const ordersFlat = [',
          '  {',
          '    orderId: 1,',
          "    customerName: 'Alice',",
          "    customerCity: 'Jakarta',",
          "    productName: 'Keyboard',",
          "    categoryName: 'Electronics',",
          '  },',
          '  {',
          '    orderId: 1,',
          "    customerName: 'Alice',",
          "    customerCity: 'Jakarta',",
          "    productName: 'Mouse',",
          "    categoryName: 'Electronics',",
          '  },',
          ']',
          '',
          '// Bentuk normalisasi',
          'const customers = [{ customerId: 10, name: \'Alice\', city: \'Jakarta\' }]',
          'const categories = [{ categoryId: 20, name: \'Electronics\' }]',
          'const products = [',
          '  { productId: 100, name: \'Keyboard\', categoryId: 20 },',
          '  { productId: 101, name: \'Mouse\', categoryId: 20 },',
          ']',
          'const orderItems = [',
          '  { orderId: 1, productId: 100 },',
          '  { orderId: 1, productId: 101 },',
          ']',
          '',
          "console.log('Redundansi city di flat:', ordersFlat.filter((o) => o.customerName === 'Alice').length, 'kali')",
          "console.log('Customers tersimpan sekali:', customers.length)",
        ].join('\n'),
        explanation:
          'Flat table menyimpan customerCity berulang untuk setiap item order. Setelah normalisasi, data pelanggan dan kategori disimpan satu kali, lalu dihubungkan melalui FK.',
      },
    },
    {
      id: 'sec-04-intermediate-fd-bcnf',
      type: 'markdown',
      level: 'intermediate',
      title: 'Functional Dependency dan BCNF',
      content: `## Functional Dependency\n\nFunctional dependency ditulis \`A → B\` yang berarti nilai A secara unik menentukan nilai B.\n\n- **Determinant**: sisi kiri (A).\n- **Dependent**: sisi kanan (B).\n- Jika \`A → B\` dan \`B → C\`, maka \`A → C\` secara transitif.\n\n## BCNF — Boyce-Codd Normal Form\n\nSebuah table memenuhi BCNF jika untuk setiap functional dependency \`X → Y\`, \`X\` adalah superkey.\n\nContoh pelanggaran BCNF:\n\nstudent_id → student_name\nclass_id → class_name\nstudent_id, class_id → grade\n\nJika PK adalah \`(student_id, class_id)\`, maka \`class_id → class_name\` melanggar BCNF karena \`class_id\` bukan superkey. Solusinya: pisahkan menjadi table \`Classes(class_id, class_name)\`.\n\n## Kapan BCNF Lebih Penting dari 3NF?\n\nJika sebuah table memenuhi 3NF tetapi tidak BCNF, masih mungkin terjadi anomali karena determinant bukan superkey. BCNF menghilangkan semua anomali akibat functional dependency. Namun, BCNF kadang harus mengorbankan dependency preservation, sehingga join diperlukan untuk memvalidasi determinan.`,
    },
    {
      id: 'sec-04-ts-example',
      type: 'code-example',
      codeExample: {
        id: 'code-04-ts',
        filename: 'normalizer.ts',
        language: 'typescript',
        title: 'TypeScript: Deteksi Partial Dependency',
        code: [
          'interface FlatOrder {',
          '  orderId: number',
          '  productId: number',
          '  orderDate: string // tergantung pada orderId saja',
          '  productName: string // tergantung pada productId saja',
          '  quantity: number // tergantung pada orderId + productId',
          '}',
          '',
          '// orderDate hanya bergantung pada orderId, bukan seluruh composite key (orderId, productId)',
          '// => melanggar 2NF',
          '',
          'interface Order {',
          '  orderId: number',
          '  orderDate: string',
          '}',
          '',
          'interface Product {',
          '  productId: number',
          '  productName: string',
          '}',
          '',
          'interface OrderItem {',
          '  orderId: number',
          '  productId: number',
          '  quantity: number',
          '}',
          '',
          'const orders: Order[] = []',
          'const products: Product[] = []',
          'const orderItems: OrderItem[] = []',
          '',
          'function addItem(o: Order, p: Product, qty: number) {',
          '  if (!orders.find((x) => x.orderId === o.orderId)) orders.push(o)',
          '  if (!products.find((x) => x.productId === p.productId)) products.push(p)',
          '  orderItems.push({ orderId: o.orderId, productId: p.productId, quantity: qty })',
          '}',
          '',
          "addItem({ orderId: 1, orderDate: '2026-06-01' }, { productId: 100, productName: 'Keyboard' }, 2)",
          'console.log(orders, products, orderItems)',
        ].join('\n'),
        explanation:
          'Memecah flat order menjadi Order, Product, dan OrderItem menghilangkan partial dependency. Setiap atribut non-key sekarang bergantung penuh pada PK table-nya.',
      },
    },
    {
      id: 'sec-04-advanced-denormalization',
      type: 'markdown',
      level: 'advanced',
      title: 'Denormalisasi dan Higher Normal Forms',
      content: `## Denormalisasi\n\nDenormalisasi adalah kebalikan normalisasi: sengaja menambahkan redundansi untuk mempercepat query baca.\n\nKapan denormalisasi masuk akal:\n\n- Read-heavy workload dengan query kompleks.\n- Report atau analytics yang jarang berubah.\n- Cache materialized untuk dashboard.\n- Data warehouse (umumnya denormalized/star schema).\n\nRisiko denormalisasi:\n\n- Update menjadi lebih kompleks dan rentan anomali.\n- Memerlukan mekanisme sinkronisasi (trigger, batch, atau CDC).\n- Lebih banyak ruang disk.\n\n## 4NF dan 5NF\n\n- **4NF (Fourth Normal Form)**: menghilangkan multi-valued dependency. Contoh: jika satu pegawai bisa memiliki banyak skill dan banyak proyek yang tidak saling bergantung, sebaiknya dipisah.\n- **5NF (Fifth Normal Form / Project-Join Normal Form)**: menghilangkan join dependency yang tidak dapat diturunkan dari candidate keys. Digunakan untuk menghindari anomali join pada skema kompleks.\n\nDalam praktik industri, 3NF/BCNF sudah cukup untuk kebanyakan aplikasi OLTP. 4NF dan 5NF lebih sering dibahas dalam konteks akademis atau desain database sangat kompleks.`,
    },
    {
      id: 'sec-04-go-example',
      type: 'code-example',
      codeExample: {
        id: 'code-04-go',
        filename: 'main.go',
        language: 'go',
        title: 'Go: Normalisasi Model E-commerce',
        code: [
          'package main',
          '',
          'import "fmt"',
          '',
          'type Customer struct {',
          '\tCustomerID int64',
          '\tName       string',
          '\tCity       string',
          '}',
          '',
          'type Category struct {',
          '\tCategoryID int64',
          '\tName       string',
          '}',
          '',
          'type Product struct {',
          '\tProductID  int64',
          '\tCategoryID int64',
          '\tName       string',
          '}',
          '',
          'type Order struct {',
          '\tOrderID    int64',
          '\tCustomerID int64',
          '}',
          '',
          'type OrderItem struct {',
          '\tOrderID   int64',
          '\tProductID int64',
          '\tQuantity  int',
          '}',
          '',
          'func main() {',
          '\tc := Customer{CustomerID: 1, Name: "Alice", City: "Jakarta"}',
          '\tcat := Category{CategoryID: 10, Name: "Electronics"}',
          '\tp := Product{ProductID: 100, CategoryID: cat.CategoryID, Name: "Keyboard"}',
          '\to := Order{OrderID: 1000, CustomerID: c.CustomerID}',
          '\titem := OrderItem{OrderID: o.OrderID, ProductID: p.ProductID, Quantity: 2}',
          '\tfmt.Printf("Order %d oleh %s memiliki %d x %s\\n", o.OrderID, c.Name, item.Quantity, p.Name)',
          '}',
        ].join('\n'),
        explanation:
          'Setiap entitas memiliki satu tanggung jawab. Relasi many-to-many antara Order dan Product diwakili oleh OrderItem. Tidak ada redundansi data pelanggan atau kategori.',
      },
    },
    {
      id: 'sec-04-summary',
      type: 'callout',
      calloutType: 'info',
      content:
        '**Kesimpulan:** Normalisasi mengurangi redundansi dan anomali. Mulailah dari 3NF/BCNF untuk aplikasi transaksional, lalu denormalisasi secara sadar untuk kebutuhan performa baca berdasarkan data akses pattern.',
    },
  ],
}
