import type { Lesson } from '@/content/types'

export const ch05Lesson: Lesson = {
  id: 'lesson-ch-05-btrees-storage-engines-index-internals',
  estimatedMinutes: 55,
  sections: [
    {
      id: 'sec-05-basic-btree',
      type: 'markdown',
      level: 'basic',
      title: 'Struktur B+ Tree',
      content: `## Apa itu B+ Tree?\n\nB+ tree adalah struktur data self-balancing tree yang paling umum digunakan untuk index database. Setiap node berisi beberapa key yang terurut.\n\n- **Internal node**: menyimpan key dan pointer ke child node; tidak menyimpan data aktual.\n- **Leaf node**: menyimpan key dan record identifier (RID) atau row data itu sendiri.\n- **Linked leaves**: leaf node di B+ tree saling terhubung melalui pointer, sehingga range scan tidak perlu kembali ke root.\n\n## Mengapa B+ Tree?\n\n- Pencarian key memakan waktu O(log n).\n- Selalu balanced, sehingga performa query prediktabil.\n- Efisien untuk range query karena leaf node terurut dan terhubung.\n- Cocok dengan block-based storage karena satu node biasanya berukuran satu page disk (misalnya 4 KB atau 8 KB).\n\n## Page dan Node Layout\n\nPage adalah unit I/O terkecil. Sebuah page dapat menampung beberapa entry. Ketika page penuh karena insert, terjadi **page split**: satu page dipecah menjadi dua dan key tengah naik ke parent. Page split menyebabkan write amplification karena beberapa page harus ditulis ulang.`,
    },
    {
      id: 'sec-05-js-example',
      type: 'code-example',
      codeExample: {
        id: 'code-05-js',
        filename: 'btree-simulation.js',
        language: 'javascript',
        title: 'JavaScript: Simulasi Pencarian pada B+ Tree',
        code: [
          'const leafA = [',
          '  { key: 10, value: \'row-10\' },',
          '  { key: 20, value: \'row-20\' },',
          ']',
          'const leafB = [',
          '  { key: 30, value: \'row-30\' },',
          '  { key: 40, value: \'row-40\' },',
          ']',
          'const root = [',
          '  { key: 30, left: leafA, right: leafB },',
          ']',
          '',
          'function btreeSearch(rootNodes, target) {',
          '  const node = rootNodes[0]',
          '  const leaf = target < node.key ? node.left : node.right',
          '  return leaf.find((entry) => entry.key === target)',
          '}',
          '',
          'console.log(btreeSearch(root, 30))',
          'console.log(btreeSearch(root, 20))',
        ].join('\n'),
        explanation:
          'Contoh sederhana ini mengilustrasikan traversal B+ tree: bandingkan key di internal node, pilih leaf yang tepat, lalu cari key di leaf.',
      },
    },
    {
      id: 'sec-05-intermediate-index-types',
      type: 'markdown',
      level: 'intermediate',
      title: 'Jenis Index dan Composite Index',
      content: `## Clustered vs Non-Clustered Index\n\n- **Clustered index**: data row disimpan secara fisik mengikuti urutan key. Setiap table biasanya hanya memiliki satu clustered index. Di MySQL InnoDB, primary key adalah clustered index; di PostgreSQL, table disimpan sebagai heap dan primary key adalah non-clustered B-tree.\n- **Non-clustered index**: menyimpan key dan pointer (atau PK) ke row asli. Dibutuhkan lookup tambahan untuk mengambil kolom lain.\n\n## Heap vs Index-Organized Table\n\n- **Heap table** (PostgreSQL, SQL Server default): row disimpan tanpa urutan khusus; index hanya menunjuk ke TID/row ID.\n- **Index-organized table** (InnoDB clustered PK): row disimpan di dalam leaf B-tree, sehingga PK lookup sangat cepat tetapi secondary index membutuhkan PK untuk menemukan row.\n\n## Composite Index dan Column Ordering\n\nComposite index memiliki lebih dari satu kolom. Urutan kolom sangat penting. Contoh: CREATE INDEX idx_orders_user_date ON orders(user_id, order_date);\n\nIndex di atas dapat digunakan untuk:\n\n- \`WHERE user_id = 5\`\n- \`WHERE user_id = 5 AND order_date > '2026-01-01'\`\n\nTetapi tidak efisien untuk:\n\n- \`WHERE order_date > '2026-01-01'\` (tidak menggunakan prefix kiri).\n\n## Covering Index dan Index-Only Scan\n\nCovering index mencakup semua kolom yang dibutuhkan query. Database dapat menjawab query hanya dari index tanpa mengakses heap/table, disebut **index-only scan**. Ini mengurangi I/O secara signifikan.`,
    },
    {
      id: 'sec-05-ts-example',
      type: 'code-example',
      codeExample: {
        id: 'code-05-ts',
        filename: 'index-planner.ts',
        language: 'typescript',
        title: 'TypeScript: Memeriksa Penggunaan Composite Index',
        code: [
          'type Predicate =',
          "  | { column: string; op: '=' | '>' | '<'; value: unknown }",
          "  | { column: string; op: 'IN'; values: unknown[] }",
          '',
          'interface IndexDef {',
          '  name: string',
          '  columns: string[]',
          '}',
          '',
          'function canUseIndex(index: IndexDef, predicates: Predicate[]): boolean {',
          '  const predicateColumns = new Set(predicates.map((p) => p.column))',
          '  // Prefix match: index columns harus muncul secara berurutan dari kiri',
          '  for (let i = 0; i < index.columns.length; i++) {',
          '    if (!predicateColumns.has(index.columns[i])) {',
          '      // jika kolom pertama tidak ada, index tidak terpakai sama sekali',
          '      return i > 0',
          '    }',
          '  }',
          '  return true',
          '}',
          '',
          "const idx = { name: 'idx_user_date', columns: ['user_id', 'order_date'] }",
          '',
          "console.log(canUseIndex(idx, [{ column: 'user_id', op: '=', value: 5 }]))",
          '// true',
          "console.log(canUseIndex(idx, [{ column: 'order_date', op: '>', value: '2026-01-01' }]))",
          '// false',
        ].join('\n'),
        explanation:
          'Fungsi sederhana ini memeriksa apakah predicate query cocok dengan prefix kiri composite index. Di database sesungguhnya, optimizer mempertimbangkan sebaran data, selectivity, dan cost model.',
      },
    },
    {
      id: 'sec-05-advanced-storage-engines',
      type: 'markdown',
      level: 'advanced',
      title: 'Storage Engines, WAL, dan Page Split',
      content: `## Perbandingan Storage Engine\n\n### InnoDB (MySQL)\n\n- Table disimpan sebagai clustered index di primary key.\n- Secondary index menyimpan primary key value di leaf (tidak langsung row pointer).\n- Mendukung MVCC melalui undo log.\n- Buffer pool menyimpan page data dan index di memori.\n\n### PostgreSQL Heapam\n\n- Table disimpan sebagai heap, tidak terurut.\n- Primary key adalah B-tree biasa yang menyimpan TID (block number, offset number).\n- Index-only scan membutuhkan visibility map agar tidak perlu memeriksa heap.\n- TOAST menangani kolom besar yang tidak muat di page.\n\n### SQLite B-tree\n\n- Table default adalah B-tree tanpa separate clustered index.\n- Row ID atau INTEGER PRIMARY KEY bertindak sebagai key B-tree.\n- Sangat ringan, satu file database, cocok untuk embedded.\n\n## Write-Ahead Log (WAL)\n\nWAL adalah teknik di mana setiap modifikasi pertama kali ditulis ke log sequensial sebelum diaplikasikan ke page data. Manfaat:\n\n1. **Durability**: log yang sudah fsync akan bertahan meskipun crash.\n2. **Atomicity**: recovery dapat mengulang (redo) atau membatalkan (undo) perubahan.\n3. **Performa**: penulisan sequensial lebih cepat daripada random write ke page.\n\n## Page Split dan Fragmentation\n\nKetika B-tree node penuh dan ada insert di tengah:\n\n1. Node dipecah menjadi dua.\n2. Key tengah dipromosikan ke parent.\n3. Jika parent penuh, split berlanjut ke atas hingga root.\n\nPage split menyebabkan:\n\n- Write amplification: banyak page disk ditulis.\n- Fragmentasi: page tidak terisi penuh, mengurangi density data.\n- Solusi: pilih PK monoton (seperti BIGSERIAL) untuk insert di ujung kanan B-tree, mengurangi split di tengah.\n\n## Selectivity dan Cardinality Estimation\n\nOptimizer menggunakan statistik (histogram, distinct values, correlation) untuk memperkirakan jumlah row yang cocok. Index dengan selectivity rendah (misalnya kolom gender dengan dua nilai) mungkin tidak dipilih karena sequential scan lebih murah.`,
    },
    {
      id: 'sec-05-go-example',
      type: 'code-example',
      codeExample: {
        id: 'code-05-go',
        filename: 'main.go',
        language: 'go',
        title: 'Go: Strategi Index untuk Query Order',
        code: [
          'package main',
          '',
          'import (',
          '\t"database/sql"',
          '\t"fmt"',
          '\t"log"',
          '',
          '\t_ "github.com/lib/pq"',
          ')',
          '',
          'func main() {',
          '\tdb, err := sql.Open("postgres", "postgres://user:pass@localhost/shop?sslmode=disable")',
          '\tif err != nil {',
          '\t\tlog.Fatal(err)',
          '\t}',
          '\tdefer db.Close()',
          '',
          '\t// Composite index: (user_id, order_date)',
          '\t// Query yang cocok dengan prefix kiri',
          '\trows, err := db.Query(',
          '\t\t"SELECT order_id, total " +',
          '\t\t"FROM orders " +',
          '\t\t"WHERE user_id = $1 AND order_date >= $2 " +',
          '\t\t"ORDER BY order_date",',
          '\t\t42, "2026-01-01",',
          '\t)',
          '\tif err != nil {',
          '\t\tlog.Fatal(err)',
          '\t}',
          '\tdefer rows.Close()',
          '',
          '\tcount := 0',
          '\tfor rows.Next() {',
          '\t\tcount++',
          '\t}',
          '\tfmt.Printf("Rows untuk user 42: %d\\n", count)',
          '',
          '\t// Di PostgreSQL, EXPLAIN ANALYZE dapat memverifikasikan apakah index terpakai',
          '\t_, _ = db.Exec("EXPLAIN ANALYZE SELECT order_id FROM orders WHERE user_id = $1", 42)',
          '}',
        ].join('\n'),
        explanation:
          'Composite index (user_id, order_date) mendukung predicate equality pada user_id dan range pada order_date. Gunakan EXPLAIN ANALYZE untuk memverifikasi execution plan.',
      },
    },
    {
      id: 'sec-05-summary',
      type: 'callout',
      calloutType: 'info',
      content:
        '**Kesimpulan:** B+ tree adalah fondasi indexing relasional. Pahami page layout, clustered vs non-clustered, composite index prefix rule, dan peran WAL. Rancang index berdasarkan query pattern, lalu verifikasi dengan EXPLAIN ANALYZE.',
    },
  ],
}
