import type { Lesson } from '@/content/types'

export const ch01Lesson: Lesson = {
  id: 'lesson-ch-01-relational-model-er-diagram',
  estimatedMinutes: 40,
  sections: [
    {
      id: 'sec-01-basic-relational-model',
      type: 'markdown',
      level: 'basic',
      title: 'Komponen Model Relasional',
      content: `## Table, Row, dan Column\n\nDatabase relasional menyimpan data dalam **table** (juga disebut *relation*). Setiap table terdiri dari:\n\n- **Row / Tuple**: satu record atau satu entitas, misalnya satu pengguna.\n- **Column / Attribute**: field atau sifat dari entitas, misalnya nama atau email.\n- **Domain**: himpunan nilai yang valid untuk sebuah column, misalnya email harus mengandung \`@\`.\n\n## Key\n\nKey adalah column atau kombinasi column yang digunakan untuk mengidentifikasi atau menghubungkan data.\n\n- **Primary Key (PK)**: column yang secara unik mengidentifikasi setiap row. Nilainya tidak boleh NULL dan tidak boleh duplikat.\n- **Foreign Key (FK)**: column yang merujuk ke PK di table lain untuk menjaga hubungan antar table.\n- **Candidate Key**: semua column atau kombinasi column yang bisa menjadi PK.\n- **Composite Key**: PK yang terdiri dari lebih dari satu column.\n\n## Entity-Relationship (ER) Diagram\n\nER Diagram adalah representasi visual dari entitas, atribut, dan relasi antar entitas. Sebelum menulis SQL, perancang database biasanya membuat ERD untuk memvalidasi pemahaman domain.\n\nElemen utama ERD:\n\n1. **Entitas**: objek nyata atau konseptual, misalnya \`User\`, \`Order\`, \`Product\`.\n2. **Atribut**: sifat entitas, bisa berupa key atau atribut biasa.\n3. **Relasi**: hubungan antar entitas yang diberi label sesuai maknanya.\n4. **Cardinality**: berapa banyak record di satu sisi yang berhubungan dengan record di sisi lain.`,
    },
    {
      id: 'sec-01-js-example',
      type: 'code-example',
      codeExample: {
        id: 'code-01-js',
        filename: 'schema.js',
        language: 'javascript',
        title: 'JavaScript: Model Data Sederhana',
        code: [
          'const users = [',
          '  { userId: 1, email: \'alice@example.com\', name: \'Alice\' },',
          '  { userId: 2, email: \'bob@example.com\', name: \'Bob\' },',
          ']',
          '',
          'const orders = [',
          '  { orderId: 101, userId: 1, total: 250000 },',
          '  { orderId: 102, userId: 2, total: 120000 },',
          ']',
          '',
          'function getOrdersByUser(userId) {',
          '  return orders.filter((order) => order.userId === userId)',
          '}',
          '',
          'console.log(getOrdersByUser(1))',
          '// [{ orderId: 101, userId: 1, total: 250000 }]',
        ].join('\n'),
        explanation:
          'Array of objects ini mengilustrasikan dua table relasional. userId di orders adalah foreign key yang merujuk ke users.userId. Filter menghasilkan hubungan one-to-many sederhana.',
      },
    },
    {
      id: 'sec-01-intermediate-er-notation',
      type: 'markdown',
      level: 'intermediate',
      title: 'Notasi ER dan Cardinality',
      content: `## Notasi Crow's Foot\n\nNotasi Crow's Foot menggunakan simbol kaki burung untuk menunjukkan "banyak" dan garis tunggal untuk "satu". Contoh:\n\n- \`User ||---o< Order\`: satu user dapat memiliki banyak order; setiap order dimiliki oleh satu user.\n- \`User ||---|| Profile\`: satu user memiliki tepat satu profile, dan satu profile dimiliki oleh tepat satu user.\n- \`Order >---< Product\` melalui tabel penghubung \`OrderItem\`: satu order bisa berisi banyak product; satu product bisa muncul di banyak order.\n\n## Jenis Relasi\n\n- **One-to-One (1:1)**: setiap entitas di sisi A berhubungan dengan tepat satu entitas di sisi B. Biasanya dipakai untuk data opsional atau pemisahan kolom sensitif.\n- **One-to-Many (1:N)**: satu record di sisi A dapat berhubungan dengan banyak record di sisi B. Contoh: satu \`Category\` memiliki banyak \`Product\`.\n- **Many-to-Many (M:N)**: banyak record di kedua sisi bisa saling berhubungi. Di database relasional, relasi ini diwakili oleh **junction table** atau **associative table**.\n\n## Weak Entity\n\nWeak entity adalah entitas yang tidak dapat diidentifikasi secara unik hanya dengan atributnya sendiri, melainkan membutuhkan PK dari entitas induk. Contoh: \`OrderItem\` membutuhkan \`orderId\` untuk memiliki makna.`,
    },
    {
      id: 'sec-01-ts-example',
      type: 'code-example',
      codeExample: {
        id: 'code-01-ts',
        filename: 'schema.ts',
        language: 'typescript',
        title: 'TypeScript: Tipe Relasi ER',
        code: [
          'type User = {',
          '  userId: number',
          '  email: string',
          '  name: string',
          '}',
          '',
          'type Order = {',
          '  orderId: number',
          '  userId: number // FK → User.userId',
          '  total: number',
          '}',
          '',
          'type Product = {',
          '  productId: number',
          '  name: string',
          '  price: number',
          '}',
          '',
          'type OrderItem = {',
          '  orderItemId: number',
          '  orderId: number // FK → Order.orderId',
          '  productId: number // FK → Product.productId',
          '  quantity: number',
          '}',
          '',
          'function ordersWithItems(',
          '  orders: Order[],',
          '  items: OrderItem[],',
          '  products: Product[]',
          ') {',
          '  return orders.map((order) => ({',
          '    ...order,',
          '    items: items',
          '      .filter((item) => item.orderId === order.orderId)',
          '      .map((item) => ({',
          '        ...item,',
          '        product: products.find((p) => p.productId === item.productId),',
          '      })),',
          '  }))',
          '}',
          '',
          'const result = ordersWithItems([], [], [])',
          'console.log(result)',
        ].join('\n'),
        explanation:
          'Tipe eksplisit FK menjaga konsistensi relasi saat refactor. Junction table OrderItem memutuskan relasi many-to-many antara Order dan Product menjadi dua relasi one-to-many.',
      },
    },
    {
      id: 'sec-01-advanced-key-design',
      type: 'markdown',
      level: 'advanced',
      title: 'Surrogate Key vs Natural Key dan Domain Modeling',
      content: `## Surrogate Key\n\nSurrogate key adalah key buatan yang tidak memiliki makna bisnis, umumnya berupa auto-increment integer atau UUID.\n\nKelebihan:\n\n- Stabil: tidak berubah meskipun data bisnis berubah.\n- Sederhana dan kecil, efisien sebagai referensi PK/FK.\n- Tidak mengandung informasi sensitif.\n\nKekurangan:\n\n- Tidak bermakna bagi pengguna atau auditor.\n- Dapat menyebabkan duplikasi logis jika tidak diikuti unique constraint pada atribut bisnis.\n\n## Natural Key\n\nNatural key berasal dari atribut yang memang mengidentifikasi entitas di dunia nyata, seperti NIK atau nomor ISBN.\n\nKelebihan:\n\n- Bermakna dan mudah diaudit.\n- Mengurangi jumlah column karena tidak perlu surrogate.\n\nKekurangan:\n\n- Bisa berubah, sehingga cascade update di banyak table menjadi mahal.\n- Bisa panjang dan tidak standar, membuat index lebih besar.\n\n## Domain Modeling dan Subtypes\n\nDomain modeling adalah proses memahami aturan bisnis lalu menerjemahkannya ke entitas dan relasi. Pola subtype memungkinkan entitas umum dibagi menjadi beberapa spesialisasi:\n\n- **Single Table Inheritance**: satu table untuk semua subtype, dengan discriminator column.\n- **Class Table Inheritance**: table induk + table khusus per subtype.\n- **Concrete Table Inheritance**: setiap subtype memiliki table lengkap sendiri.\n\nPilihan bergantung pada seberapa banyak atribut yang berbeda, seberapa sering query menyertakan semua subtype, dan kebutuhan integritas referensial.`,
    },
    {
      id: 'sec-01-go-example',
      type: 'code-example',
      codeExample: {
        id: 'code-01-go',
        filename: 'main.go',
        language: 'go',
        title: 'Go: Struct Mapping untuk ERD E-commerce',
        code: [
          'package main',
          '',
          'import "fmt"',
          '',
          'type User struct {',
          '\tUserID int64',
          '\tEmail  string',
          '\tName   string',
          '}',
          '',
          'type Product struct {',
          '\tProductID int64',
          '\tName      string',
          '\tPrice     int64',
          '}',
          '',
          'type Order struct {',
          '\tOrderID int64',
          '\tUserID  int64',
          '\tTotal   int64',
          '}',
          '',
          'type OrderItem struct {',
          '\tOrderItemID int64',
          '\tOrderID     int64',
          '\tProductID   int64',
          '\tQuantity    int',
          '}',
          '',
          'func main() {',
          '\tu := User{UserID: 1, Email: "alice@example.com", Name: "Alice"}',
          '\to := Order{OrderID: 101, UserID: u.UserID, Total: 250000}',
          '\tfmt.Printf("%s memiliki order #%d sebesar Rp%d\\n", u.Name, o.OrderID, o.Total)',
          '}',
        ].join('\n'),
        explanation:
          'Struct Go menggambarkan entitas dari ERD. Field UserID di Order merepresentasikan foreign key. Relasi many-to-many Order-Product dipecah menjadi OrderItem sebagai junction table.',
      },
    },
    {
      id: 'sec-01-summary',
      type: 'callout',
      calloutType: 'info',
      content:
        '**Kesimpulan:** Rancang ERD sebelum menulis SQL. Pahami cardinality, pilih key dengan bijak, dan pertimbangkan trade-off surrogate vs natural key. Domain modeling yang baik mengurangi de-normalisasi berlebihan dan mempermudah pemeliharaan skema jangka panjang.',
    },
  ],
}
