import type { Lesson } from '@/content/types'

export const ch06Lesson: Lesson = {
  id: 'lesson-ch-06-transactions-acid',
  estimatedMinutes: 55,
  sections: [
    {
      id: 'sec-06-basic-acid',
      type: 'markdown',
      level: 'basic',
      title: 'Transaksi dan ACID',
      content: `## Apa itu Transaksi?\n\nTransaksi adalah satu unit kerja yang terdiri dari satu atau beberapa operasi SQL. Transaksi harus memenuhi sifat ACID. Contoh transfer dana menggunakan BEGIN, UPDATE dua kali, lalu COMMIT.\n\n## Sifat ACID\n\n- **Atomicity**: semua operasi dalam transaksi berhasil, atau tidak ada yang berhasil. Jika terjadi kegagalan, database melakukan rollback.\n- **Consistency**: transaksi membawa database dari satu state valid ke state valid lainnya sesuai constraint.\n- **Isolation**: transaksi yang berjalan bersamaan seolah-olah dieksekusi secara terpisah.\n- **Durability**: setelah COMMIT, perubahan bertahan meskipun terjadi crash.\n\n## Tingkat Isolasi\n\n1. **READ UNCOMMITTED**: bisa membaca perubahan yang belum di-commit (dirty read).\n2. **READ COMMITTED**: hanya membaca data yang sudah di-commit.\n3. **REPEATABLE READ**: membaca data yang sama berkali dalam transaksi memberikan hasil yang sama.\n4. **SERIALIZABLE**: eksekusi transaksi seolah-olah serial, paling aman tetapi paling lambat.`,
    },
    {
      id: 'sec-06-js-example',
      type: 'code-example',
      codeExample: {
        id: 'code-06-js',
        filename: 'transfer.js',
        language: 'javascript',
        title: 'JavaScript: Simulasi Transfer Atomik',
        code: [
          'const accounts = {',
          '  A: 500000,',
          '  B: 300000,',
          '}',
          '',
          'function transfer(from, to, amount) {',
          '  if (accounts[from] < amount) {',
          "    throw new Error('Saldo tidak cukup')",
          '  }',
          '  accounts[from] -= amount',
          '  accounts[to] += amount',
          '}',
          '',
          'try {',
          "  transfer('A', 'B', 100000)",
          '  console.log(\'Transfer berhasil:\', accounts)',
          '} catch (err) {',
          '  console.error(\'Transfer gagal, saldo tidak berubah:\', accounts)',
          '}',
        ].join('\n'),
        explanation:
          'Di aplikasi murni, transfer gagal akan membatalkan seluruh perubahan. Database transaksi menjamin hal yang sama bahkan jika crash terjadi di tengah.',
      },
    },
    {
      id: 'sec-06-intermediate-anomalies',
      type: 'markdown',
      level: 'intermediate',
      title: 'Anomali Isolasi',
      content: `## Dirty Read\n\nTransaksi A mengubah data tetapi belum COMMIT. Transaksi B membaca data tersebut. Jika A kemudian ROLLBACK, B telah membaca data yang tidak pernah valid.\n\n## Non-Repeatable Read\n\nDalam satu transaksi, membaca row yang sama dua kali menghasilkan nilai berbeda karena transaksi lain mengubah dan commit di antaranya.\n\n## Phantom Read\n\nDalam satu transaksi, query yang sama dieksekusi dua kali dan menghasilkan set row berbeda karena transaksi lain menambah atau menghapus row.\n\n## Tingkat Isolasi vs Anomali\n\n| Isolasi | Dirty Read | Non-Repeatable | Phantom |\n|---|---|---|---|\n| READ UNCOMMITTED | Mungkin | Mungkin | Mungkin |\n| READ COMMITTED | Dilarang | Mungkin | Mungkin |\n| REPEATABLE READ | Dilarang | Dilarang | Mungkin* |\n| SERIALIZABLE | Dilarang | Dilarang | Dilarang |\n\n* Di PostgreSQL, REPEATABLE READ sebenarnya mencegah phantom read melalui snapshot; di MySQL InnoDB default REPEATABLE READ juga mencegah phantom untuk index lock.\n\n## Pessimistic vs Optimistic Locking\n\n- **Pessimistic locking**: mengunci row/table saat dibaca untuk mencegah konflik.\n- **Optimistic locking**: tidak mengunci; saat commit, memeriksa apakah data berubah, biasanya dengan version number atau timestamp.`,
    },
    {
      id: 'sec-06-ts-example',
      type: 'code-example',
      codeExample: {
        id: 'code-06-ts',
        filename: 'isolation.ts',
        language: 'typescript',
        title: 'TypeScript: Simulasi Optimistic Locking',
        code: [
          'interface Account {',
          '  accountId: string',
          '  balance: number',
          '  version: number',
          '}',
          '',
          'const accounts: Record<string, Account> = {',
          '  A: { accountId: \'A\', balance: 500000, version: 1 },',
          '}',
          '',
          'function updateBalance(',
          '  id: string,',
          '  expectedVersion: number,',
          '  delta: number',
          '): boolean {',
          '  const account = accounts[id]',
          '  if (!account) return false',
          '  if (account.version !== expectedVersion) {',
          '    // Data sudah berubah sejak terakhir dibaca',
          '    return false',
          '  }',
          '  account.balance += delta',
          '  account.version += 1',
          '  return true',
          '}',
          '',
          "console.log(updateBalance('A', 1, -100000)) // true",
          "console.log(updateBalance('A', 1, -50000))  // false, versi tidak cocok",
        ].join('\n'),
        explanation:
          'Optimistic locking memeriksa version sebelum menulis. Jika version berubah, aplikasi dapat mengulang membaca data. Pola ini umum di ORM dan sistem dengan konflik jarang.',
      },
    },
    {
      id: 'sec-06-advanced-mvcc-deadlock',
      type: 'markdown',
      level: 'advanced',
      title: 'MVCC dan Deadlock',
      content: `## Multiversion Concurrency Control (MVCC)\n\nMVCC memungkinkan reader membaca snapshot data tanpa menunggu writer. Setiap transaksi melihat snapshot sesuai waktu mulainya.\n\nCara kerja MVCC secara umum:\n\n1. Setiap row memiliki versi atau transaction ID (XID) untuk create dan delete.\n2. Reader memeriksa visibility: row termasuk dalam snapshot transaksi saya atau tidak.\n3. Writer membuat versi baru tanpa menghapus versi lama sebelum transaksi commit.\n4. Vacuum / purge berjalan secara berkala untuk membersihkan versi lama yang tidak lagi dibutuhkan.\n\nKeuntungan MVCC:\n\n- Reader tidak memblokir writer, dan writer tidak memblokir reader.\n- Tingkat isolasi REPEATABLE READ lebih mudah dicapai.\n- Konkurensi tinggi dengan overhead lock minimal.\n\nTantangan MVCC:\n\n- Banyak versi membutuhkan ruang dan pemeliharaan (vacuum).\n- Long-running transaction dapat memblokir vacuum dan menyebabkan table bloat di PostgreSQL.\n- Transaction ID wraparound memerlukan perhatian khusus.\n\n## Deadlock\n\nDeadlock terjadi ketika dua transaksi saling memegang lock yang dibutuhkan satu sama lain.\n\nContoh:\n\n- Transaksi 1: lock A, lalu minta lock B.\n- Transaksi 2: lock B, lalu minta lock A.\n\nDatabase mendeteksi deadlock dan membatalkan salah satu transaksi (victim). Strategi pencegahan:\n\n1. Kunci resource dalam urutan yang konsisten.\n2. Gunakan timeout dan retry di aplikasi.\n3. Hindari transaksi yang terlalu panjang.\n4. Akses row yang sama dalam urutan PK jika memungkinkan.\n\n## Snapshot Isolation dan Write Skew\n\nSnapshot isolation membaca snapshot konsisten, tetapi bisa terkena **write skew**: dua transaksi membaca overlapping data lalu masing-masing menulis sehingga constraint bisnis dilanggar. SERIALIZABLE atau explicit lock dapat mencegahnya.`,
    },
    {
      id: 'sec-06-go-example',
      type: 'code-example',
      codeExample: {
        id: 'code-06-go',
        filename: 'main.go',
        language: 'go',
        title: 'Go: Transaksi dengan sql.Tx',
        code: [
          'package main',
          '',
          'import (',
          '\t"database/sql"',
          '\t"fmt"',
          '\t"log"',
          '',
          '\t_ "github.com/lib/pq"',
          ')',
          '',
          'func transfer(db *sql.DB, from, to string, amount int64) error {',
          '\ttx, err := db.Begin()',
          '\tif err != nil {',
          '\t\treturn err',
          '\t}',
          '\t// rollback jika terjadi error sebelum commit',
          '\tdefer func() {',
          '\t\tif err != nil {',
          '\t\t\t_ = tx.Rollback()',
          '\t\t}',
          '\t}()',
          '',
          '\t_, err = tx.Exec("UPDATE accounts SET balance = balance - $1 WHERE account_id = $2", amount, from)',
          '\tif err != nil {',
          '\t\treturn err',
          '\t}',
          '\t_, err = tx.Exec("UPDATE accounts SET balance = balance + $1 WHERE account_id = $2", amount, to)',
          '\tif err != nil {',
          '\t\treturn err',
          '\t}',
          '',
          '\treturn tx.Commit()',
          '}',
          '',
          'func main() {',
          '\tdb, err := sql.Open("postgres", "postgres://user:pass@localhost/shop?sslmode=disable")',
          '\tif err != nil {',
          '\t\tlog.Fatal(err)',
          '\t}',
          '\tdefer db.Close()',
          '',
          "\tif err := transfer(db, 'A', 'B', 100000); err != nil {",
          '\t\tlog.Fatal(err)',
          '\t}',
          '\tfmt.Println("Transfer committed")',
          '}',
        ].join('\n'),
        explanation:
          'sql.Tx membungkus beberapa statement dalam satu transaksi. defer rollback memastikan transaksi dibatalkan jika terjadi error sebelum commit, menjaga atomicity.',
      },
    },
    {
      id: 'sec-06-summary',
      type: 'callout',
      calloutType: 'info',
      content:
        '**Kesimpulan:** ACID adalah jantung keandalan database. Pilih tingkat isolasi sesuai kebutuhan: READ COMMITTED untuk banyak aplikasi, REPEATABLE READ untuk laporan, SERIALIZABLE untuk keamanan ekstrem. MVCC memungkinkan konkurensi tinggi, tetapi tetap perhatikan deadlock dan long-running transaction.',
    },
  ],
}
